pipeline:
  build:
      image: python:2.7.13
      pull: true
      commands:
        - pip install -r requirements.txt
        - make html

  deploy:
    image: drillster/drone-rsync
    user: www
    hosts: [ "seel.terra.fap.no" ]
    port: 22
    source: output/
    target: /usr/local/www/kradalby.no/site/
    delete: false
    recursive: true
    exclude:
    when:
        branch: master
    script:
      - echo "Done"

  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
