build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - apt update
      - apt install npm
      - pip install -r requirements.txt
      - npm install less
      - make html

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no

deploy:
  rsync:
    user: www
    host: seel.fap.no
    port: 22
    source: output/
    target: /srv/www/kradalby.no/site/
    delete: false
    recursive: true
    exclude:
    when:
        branch: master
    commands:
      - echo "Done"
