build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - pip install -r requirements.txt
      - make html

notify:
  email:
    from: drone@fap.no
    host: mail.ntnu.fap.no
    port: 25
    recipients:
      - kradalby@kradalby.no
    when:
        branch: master

deploy:
  rsync:
    user: www
    host: seel.terra.fap.no
    port: 22
    source: output/
    target: /usr/local/www/kradalby.no/site/
    delete: false
    recursive: true
    exclude:
    when:
        branch: master
    commands:
      - echo "Done"
