pipeline:
  build:
    image: plugins/docker
    repo: kradalby/kradalby.no
    # auto_tag: true
    secrets: [ docker_username, docker_password ]
    tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: kradalby-no-deployment
    repo: kradalby/kradalby.no
    container: kradalby-no-container
    namespace: kradalby-no 
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:
      - ${DRONE_COMMIT_SHA:0:8}

  notify:
    image: drillster/drone-email
    host: smtp.fap.no
    skip_verify: true
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
